<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Huad\\Huda\\' => array($typo3InstallDir . 'typo3conf/ext/huda/Classes'),
);
